base_dir: "."

paths:
  dataset_npz: "data/processed/lyrics/training_data_40k_lyrics.npz"
  dataset_csv: "data/external/dataset_40000.csv"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  pca_path: "data/processed/lyrics/pca_40k.pkl"
  lyrics_scaler: "data/processed/lyrics/lyrics_scaler_40k.pkl"
  audio_scaler: "data/processed/lyrics/audio_scaler.pkl"
  raw_dataset_npz: "data/processed/lyrics/raw_training_data_40k_lyrics.npz"