base_dir: "."

paths:
  dataset_npz: "data/processed/training_data.npz"
  dataset_csv: "data/external/songs_dataset.csv"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  pca_path: "data/processed/pca_model.pkl"